#!/usr/bin/env perl
#! perl -T <-- how to force?

use v5.10;
use strictures 2;
use Carp;

use HC::CLI;
use HC::Graphite;


# Examine and sanitise environmant

my $cli = HC::CLI->new(path => '$ARGV[0]');

my $path = HC::CLI::_check_environment(path => (
  variable => '$ARGV[0]',
  default  => ($cli->mcwd eq '.' ? $cli->mcwd : $cli->mcwd . '.'),
));

# Find out where to really look based on the (only (optional)
# command-line argument:
#  nothing  Look in $ENV{HC_MCWD}
#  '..'     Look in the parent of $ENV{HC_MCWD} (ie. all but the last '.<thing>')
#  /^\./    Look in the absolute path given (including '.')
#  /^[^.]/  Look in the absolute path of $ENV{HC_MCWD}.<whatever>
#  /\.$/    Look for everything in $ENV{HC_MCWD} (append '*')
sub parent { shift =~ s/\.([^.]+)$//r }
my $where = substr($path,0,1) eq '.'
  ? $path
  : ($cli->mcwd eq '.' ? $cli->mcwd . $path : $cli->mcwd . ".$path");
$where = parent($cli->mcwd) . '.*' if $where eq '..';
$where .= '*' if substr($where,-1,1) eq '.';
my $graphite = HC::Graphite->new(endpoint => $cli->graphite);
my $what = $graphite->perl_metrics(find => $where)->get;

say "$where:";
for (@$what) {
  say sprintf '%s %s', ($_->{expandable} ? '+' : ' '), $_->{text};
}
